---
name: Clang Format
on: pull_request

jobs:
  clang-format:
    name: Clang Format
    runs-on: ubuntu-latest
    container: ghcr.io/rpm-software-management/dnf-ci-host
    steps:
      - name: Check out sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Rebase the pull request on target branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "Rebasing \"`git log --oneline -1`\" on ${{github.event.pull_request.base.ref}}: \"`git log --oneline -1 origin/${{github.event.pull_request.base.ref}}`\""
          git rebase origin/${{github.event.pull_request.base.ref}}

      - name: Run Clang Format
        run: |
          ./clang-format
          if [ -n "`git diff`" ]; then
            git diff --color
            echo "Clang Format detected the above coding style issues, please run the clang-format script from the repository root directory and integrate the changes into your commits."
            exit 1
          fi
